// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5dPNuhM-UoIAa5T-7dgWIzlHcI8cJXWo',
    appId: '1:523319679967:web:516d0b6c2e948f801e426a',
    messagingSenderId: '523319679967',
    projectId: 'meak-7a7fb',
    authDomain: 'meak-7a7fb.firebaseapp.com',
    storageBucket: 'meak-7a7fb.appspot.com',
    measurementId: 'G-LTXXM2EEJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcTV4myElAqcIwxP9RmVOChQNgNSqRQq8',
    appId: '1:523319679967:android:eb63accc37b0a9101e426a',
    messagingSenderId: '523319679967',
    projectId: 'meak-7a7fb',
    storageBucket: 'meak-7a7fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg6PMVKAd2xdRzabIZyrVzSom3L9C-JoE',
    appId: '1:523319679967:ios:000fad9c8fe8f2441e426a',
    messagingSenderId: '523319679967',
    projectId: 'meak-7a7fb',
    storageBucket: 'meak-7a7fb.appspot.com',
    androidClientId: '523319679967-bgnci5ikpo2ue307bh7db5cqgn9ominv.apps.googleusercontent.com',
    iosClientId: '523319679967-qk8radb3b2255gl0f17dj88nh7f6a1p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg6PMVKAd2xdRzabIZyrVzSom3L9C-JoE',
    appId: '1:523319679967:ios:000fad9c8fe8f2441e426a',
    messagingSenderId: '523319679967',
    projectId: 'meak-7a7fb',
    storageBucket: 'meak-7a7fb.appspot.com',
    androidClientId: '523319679967-bgnci5ikpo2ue307bh7db5cqgn9ominv.apps.googleusercontent.com',
    iosClientId: '523319679967-qk8radb3b2255gl0f17dj88nh7f6a1p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meak',
  );
}
